In [2]:
!pip install starrydata
!pip install pandas

Requirement already satisfied: starrydata in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (1.0.2)
Requirement already satisfied: requests in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from starrydata) (2.31.0)
Requirement already satisfied: tqdm>=4.0.0 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from starrydata) (4.66.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from requests->starrydata) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from requests->starrydata) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from requests->starrydata) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from requests->starrydata) (2024.2.2)
Requirement already satisfied: pandas in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [5]:
from starrydata.dataset import Dataset
import pandas as pd

In [19]:
dataset = Dataset(date="20240517")

2024-05-17 15:26:19,087 - INFO - Starting the download of the ZIP file.
2024-05-17 15:26:19,089 - INFO - Fetching dataset information.
2024-05-17 15:26:20,080 - INFO - Found dataset for date 20240517: 20240517_starrydata2
2024-05-17 15:26:21,073 - INFO - Downloading file: all_dataset_240517-0000.zip
2024-05-17 15:26:21,701 - WARNING - SSL verification failed, retrying without verification.
/Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxyout.nims.go.jp'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/matotomoya/dev/starrydata-python-library/.venv/lib/pypy3.9/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxyout.nims.go.jp'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-05-17 15:26:23,672 - INFO - File size: 105428022 bytes
Downloading dataset ZIP file: 100%|██████████| 101M/101M [00:22<00:00, 4.62MB/s]
2024-05-17 15:26:46,486 - INFO - Download complete. ZIP file 'all_dataset_240517-0000.zip' loaded into memory.

In [7]:
df_curves = pd.read_csv(dataset.all_curves)

In [9]:
df_curves.head()

,SID,DOI,composition,sample_id,figure_id,prop_x,prop_y,unit_x,unit_y,x,y,created_at,updated_at,project_names,comments
0,6,10.1021/am405410e,Pb1.00025Zn0.02Te1.02I0.0005,113,79,Temperature,Seebeck coefficient,K,V*K^(-1),"[""2.998597e+2"",""3.248683e+2"",""3.498757e+2"",""3....","[""-1.484452e-4"",""-1.602763e-4"",""-1.729511e-4"",...",Fri Sep 01 2017 18:19:39 GMT+0900 (JST),Fri Sep 01 2017 18:19:39 GMT+0900 (JST),"[""ThermoelectricMaterials""]",NaN
1,6006,10.1002/adma.201004200,Na0.0035Pb0.9965Se1,147,80,Temperature,Seebeck coefficient,K,V*K^(-1),"[""3.177914e+2"",""3.791411e+2"",""3.840491e+2"",""4....","[""7.275950e-5"",""7.374922e-5"",""9.257471e-5"",""1....",Fri Sep 01 2017 18:19:39 GMT+0900 (JST),Fri Sep 01 2017 18:19:39 GMT+0900 (JST),"[""ThermoelectricMaterials"",""GeneralDB""]",NaN
2,6444,10.1002/anie.200803934,Pb1.03Sb0.03Te1,434,81,Temperature,Seebeck coefficient,K,V*K^(-1),"[""3.331159e+2"",""3.405494e+2"",""3.479830e+2"",""3....","[""-2.353740e-5"",""-2.455838e-5"",""-2.681692e-5"",...",Fri Sep 01 2017 18:19:39 GMT+0900 (JST),Fri Sep 01 2017 18:19:39 GMT+0900 (JST),"[""ThermoelectricMaterials""]",NaN
3,5867,10.1016/j.actamat.2016.03.059,Pb0.76Mn0.24Te1Na0.04,248,83,Temperature,Seebeck coefficient,K,V*K^(-1),"[""3.432468e+2"",""3.763636e+2"",""4.238961e+2"",""4....","[""1.875000e-4"",""2.044481e-4"",""2.339610e-4"",""2....",Fri Sep 01 2017 18:19:39 GMT+0900 (JST),Fri Sep 01 2017 18:19:39 GMT+0900 (JST),"[""ThermoelectricMaterials""]",NaN
4,3485,10.1021/ja109138p,Pb1S0.84Te0.16Cl0.00134,389,84,Temperature,Seebeck coefficient,K,V*K^(-1),"[""3.038348e+2"",""3.209667e+2"",""3.439541e+2"",""3....","[""-9.128622e-5"",""-9.944682e-5"",""-1.051682e-4"",...",Fri Sep 01 2017 18:19:39 GMT+0900 (JST),Fri Sep 01 2017 18:19:39 GMT+0900 (JST),"[""ThermoelectricMaterials""]",NaN

In [10]:
df_samples = pd.read_csv(dataset.all_samples)

In [12]:
df_samples.head()

,sample_name,sample_id,composition,composition_details,SID,DOI,created_at,updated_at,sample_info
0,Pb1Te1I0.0006,1,Pb1Te1I0.0006,NaN,4419,10.1016/j.physb.2005.03.022,Fri Sep 01 2017 18:19:55 GMT+0900 (JST),Fri Sep 01 2017 18:19:55 GMT+0900 (JST),NaN
1,Pb1Te0.9945I0.0055,2,Pb1Te0.9945I0.0055,NaN,860,10.1039/c1ee01314a,Fri Sep 01 2017 18:19:55 GMT+0900 (JST),Fri Sep 01 2017 18:19:55 GMT+0900 (JST),"{""LaserFlash"":{""category"":"""",""comment"":""""},""Fo..."
2,In0.01Ag0.01Sn0.98Te1,3,In0.01Ag0.01Sn0.98Te1,NaN,6963,10.1063/1.4959845,Fri Sep 01 2017 18:19:55 GMT+0900 (JST),Fri Sep 01 2017 18:19:55 GMT+0900 (JST),NaN
3,Pb1.001Te1I0.002,4,Pb1.001Te1I0.002,NaN,4419,10.1016/j.physb.2005.03.022,Fri Sep 01 2017 18:19:55 GMT+0900 (JST),Fri Sep 01 2017 18:19:55 GMT+0900 (JST),NaN
4,Pb1Te0.9988I0.0012,5,Pb1Te0.9988I0.0012,NaN,860,10.1039/c1ee01314a,Fri Sep 01 2017 18:19:55 GMT+0900 (JST),Fri Sep 01 2017 18:19:55 GMT+0900 (JST),"{""LaserFlash"":{""category"":"""",""comment"":""""},""Fo..."

In [13]:
df_papers = pd.read_json(dataset.all_papers)

In [14]:
df_papers.head()

,_id,DOI,is_referenced_by_count,URL,issued,prefix,relation,subtitle,subject,author,...,status,message_version,message,message_type,language,version,categories,short_container_title,issn_type,journal_issue
0,{'$oid': '599a9700b036dfb17bdd3193'},10.1021/ar400290f,29.0,http://dx.doi.org/10.1021/ar400290f,"{'date_parts': [[2014, 4, 15]]}",10.1021,{},[],"[General Chemistry, General Medicine]","[{'affiliation': [], 'given': 'Chong', 'family...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '599a9701b036dfb17bdd3194'},10.1021/am100654p,166.0,http://dx.doi.org/10.1021/am100654p,"{'date_parts': [[2010, 11, 24]]}",10.1021,{},[],[General Materials Science],"[{'affiliation': [], 'given': 'B.', 'family': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '599a9702b036dfb17bdd3195'},10.1021/am3002764,17.0,http://dx.doi.org/10.1021/am3002764,"{'date_parts': [[2012, 6, 27]]}",10.1021,{},[],[General Materials Science],"[{'affiliation': [], 'given': 'Cham', 'family'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '599a9704b036dfb17bdd3196'},10.1021/am401444w,18.0,http://dx.doi.org/10.1021/am401444w,"{'date_parts': [[2013, 7, 24]]}",10.1021,{},[],[General Materials Science],"[{'affiliation': [], 'given': 'V.', 'family': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '599a9705b036dfb17bdd3197'},10.1021/am405035z,2.0,http://dx.doi.org/10.1021/am405035z,"{'date_parts': [[2014, 1, 22]]}",10.1021,{},[],[General Materials Science],"[{'affiliation': [], 'given': 'Cham', 'family'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
dataset.database_snapshot

'2024-05-17 00:00:01 JST+0900\n'